scope: device
workload:
  binary: benchmarks/babelstream/babelstream
  args: ["--arraysize", "2097152", "--numtimes", "100"]
  env:
    OMP_NUM_THREADS: "8"
pim:
  pe:
    type: alu_core
    count: 8
    frequency_mhz: 1000
    placement:
      level: BANK
  mc:
    type: simple
memory:
  technology: SRAM
noc:
  topology: MESH_2D
  model: simple
simulation:
  max_instructions: 1000000000
