scope: device
workload:
  binary: benchmarks/splash3/fmm/fmm
  args: ["--size", "1024", "--threads", "2"]
pim:
  pe:
    type: alu_core
    count: 2
    frequency_mhz: 1000
    placement:
      level: BANK
  mc:
    type: simple
memory:
  technology: SRAM
noc:
  topology: MESH_2D
  model: simple
simulation:
  max_instructions: 1000000
