scope: device
workload:
  binary: benchmarks/splash3/water_nsquared/water_nsquared
  args: ["--size", "512", "--threads", "4"]
pim:
  pe:
    type: alu_core
    count: 4
    frequency_mhz: 1000
    placement:
      level: BANK
  mc:
    type: simple
memory:
  technology: SRAM
noc:
  topology: MESH_2D
  model: simple
simulation:
  max_instructions: 100000000
