#ifndef PIMID_TRACE_READER_H
#define PIMID_TRACE_READER_H

#include "trace/trace_format.h"
#include <fstream>
#include <memory>
#include <vector>

namespace pimid {
namespace trace {

/**
 * @brief Trace file reader for replaying recorded simulation events
 *
 * The trace reader reads binary trace files generated by TraceWriter or
 * the trace-gen mode. It provides sequential and random access to events.
 */
class TraceReader {
public:
    TraceReader();
    ~TraceReader();

    // Non-copyable, non-movable (owns file handle)
    TraceReader(const TraceReader&) = delete;
    TraceReader& operator=(const TraceReader&) = delete;
    TraceReader(TraceReader&&) = delete;
    TraceReader& operator=(TraceReader&&) = delete;

    /**
     * @brief Open a trace file for reading
     * @param filename Input file path
     * @return true on success, false on failure
     */
    bool open(const std::string& filename);

    /**
     * @brief Close the trace file
     */
    void close();

    /**
     * @brief Check if the reader is open
     */
    bool isOpen() const { return file_.is_open(); }

    // -------------------------------------------------------------------------
    // Sequential Access
    // -------------------------------------------------------------------------

    /**
     * @brief Check if there are more events to read
     */
    bool hasNextEvent() const;

    /**
     * @brief Read the next event
     * @return The next TraceEvent
     * @throws std::runtime_error if no more events
     */
    TraceEvent readNextEvent();

    /**
     * @brief Peek at the next event without advancing
     * @return The next TraceEvent
     * @throws std::runtime_error if no more events
     */
    TraceEvent peekNextEvent();

    /**
     * @brief Read multiple events into a vector
     * @param count Maximum number of events to read
     * @return Vector of events (may be smaller than count if EOF reached)
     */
    std::vector<TraceEvent> readEvents(size_t count);

    // -------------------------------------------------------------------------
    // Random Access
    // -------------------------------------------------------------------------

    /**
     * @brief Seek to a specific event by index
     * @param index Zero-based event index
     * @return true on success, false if index out of range
     */
    bool seekToEvent(uint64_t index);

    /**
     * @brief Seek to the first event at or after the given cycle
     * @param cycle Target cycle
     * @return true on success, false if no events at/after cycle
     *
     * Note: This performs a linear scan unless an index is available.
     */
    bool seekToCycle(uint64_t cycle);

    /**
     * @brief Rewind to the beginning of the trace
     */
    void rewind();

    // -------------------------------------------------------------------------
    // Metadata Access
    // -------------------------------------------------------------------------

    /**
     * @brief Get the trace configuration metadata
     */
    const TraceConfig& getConfig() const { return config_; }

    /**
     * @brief Get the total number of events in the trace
     */
    uint64_t getTotalEvents() const { return header_.num_events; }

    /**
     * @brief Get the current event index (0-based)
     */
    uint64_t getCurrentEventIndex() const { return current_index_; }

    /**
     * @brief Get the first cycle in the trace
     */
    uint64_t getFirstCycle() const { return header_.first_cycle; }

    /**
     * @brief Get the last cycle in the trace
     */
    uint64_t getLastCycle() const { return header_.last_cycle; }

    /**
     * @brief Get the number of PEs in the trace
     */
    uint64_t getNumPEs() const { return header_.num_pes; }

    /**
     * @brief Get the trace version
     */
    uint16_t getVersion() const { return header_.version; }

    /**
     * @brief Get the input filename
     */
    const std::string& getFilename() const { return filename_; }

    // -------------------------------------------------------------------------
    // Validation
    // -------------------------------------------------------------------------

    /**
     * @brief Validate the trace file format
     * @return true if valid, false otherwise
     */
    bool validate() const;

    /**
     * @brief Get the file size in bytes
     */
    uint64_t getFileSize() const { return file_size_; }

    /**
     * @brief Calculate expected file size based on header
     */
    uint64_t getExpectedFileSize() const {
        return header_.header_size + (header_.num_events * sizeof(TraceEvent));
    }

private:
    std::ifstream file_;
    std::string filename_;
    TraceHeader header_;
    TraceConfig config_;
    uint64_t current_index_;
    uint64_t events_offset_;      // File offset where binary events start
    uint64_t file_size_;

    // Internal helpers
    bool readHeader();
    bool parseYAMLMetadata(const std::string& yaml_text);
    TraceEvent readEventAt(uint64_t index);
};

}  // namespace trace
}  // namespace pimid

#endif  // PIMID_TRACE_READER_H
